package org.ual.hmis.ortega2;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SailsLoginTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    // Browser selector
    int browser = 0; // 0: firefox, 1: chrome,...

    @Before
    public void setUp() {
        Boolean headless = true;
        switch (browser) {
        case 0: // firefox
            // Firefox
            // Descargar geckodriver de https://github.com/mozilla/geckodriver/releases
            // Descomprimir el archivo geckodriver.exe en la carpeta drivers

            System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
            FirefoxOptions firefoxOptions = new FirefoxOptions();
            if (headless)
                firefoxOptions.setHeadless(headless);
            driver = new FirefoxDriver(firefoxOptions);

            break;
        case 1: // chrome
            // Chrome
            // Descargar Chromedriver de https://chromedriver.chromium.org/downloads
            // Descomprimir el archivo chromedriver.exe en la carpeta drivers

            System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
            ChromeOptions chromeOptions = new ChromeOptions();
            if (headless)
                chromeOptions.setHeadless(headless);
            chromeOptions.addArguments("window-size=1920,1080");
            driver = new ChromeDriver(chromeOptions);

            break;

        default:
            fail("Please select a browser");
            break;
        }
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        if (browser == 1)
            driver.quit();
    }

    @Test
    public void logincorrect() {
        // Test name: Login correct
        // Step # | name | target | value
        // 1 | open | http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/ |
        driver.get("http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/");
        // 2 | waitForElementPresent | linkText=Log in | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Log in")));
        }
        // 3 | click | linkText=Log in |
        driver.findElement(By.linkText("Log in")).click();
        // 4 | waitForElementPresent | css=.form-group:nth-child(1) > .form-control |
        // 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions
                    .presenceOfElementLocated(By.cssSelector(".form-group:nth-child(1) > .form-control")));
        }
        // 5 | click | css=.form-group:nth-child(1) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
        // 6 | type | css=.form-group:nth-child(1) > .form-control |
        // usuariodeprueba@mail.es
        driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control"))
                .sendKeys("usuariodeprueba@mail.es");
        // 7 | waitForElementPresent | css=.form-group:nth-child(2) > .form-control |
        // 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions
                    .presenceOfElementLocated(By.cssSelector(".form-group:nth-child(2) > .form-control")));
        }
        // 8 | click | css=.form-group:nth-child(2) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
        // 9 | type | css=.form-group:nth-child(2) > .form-control | 123456
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("123456");
        // 10 | waitForElementPresent | css=.ajax-button | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".ajax-button")));
        }
        // 11 | click | css=.ajax-button |
        driver.findElement(By.cssSelector(".ajax-button")).click();
        // 12 | waitForElementPresent | id=header-account-menu-link | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("header-account-menu-link")));
        }
        // 13 | click | id=header-account-menu-link |
        driver.findElement(By.id("header-account-menu-link")).click();
        // 14 | waitForElementPresent | linkText=Sign out | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Sign out")));
        }
        // 15 | click | linkText=Sign out |
        driver.findElement(By.linkText("Sign out")).click();
        // 16 | pause | 1000 |
        // Pausa extra, porque hay veces que el wait for element clickable no es
        // suficiente
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 17 | close | |
        driver.close();
    }

    @Test
    public void loginincorrect() {
        // Test name: Login incorrect
        // Step # | name | target | value
        // 1 | open | http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/ |
        driver.get("http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/");
        // 2 | waitForElementPresent | linkText=Log in | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Log in")));
        }
        // 3 | click | linkText=Log in |
        driver.findElement(By.linkText("Log in")).click();
        // 4 | waitForElementPresent | css=.form-group:nth-child(1) > .form-control |
        // 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions
                    .presenceOfElementLocated(By.cssSelector(".form-group:nth-child(1) > .form-control")));
        }
        // 5 | click | css=.form-group:nth-child(1) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
        // 6 | type | css=.form-group:nth-child(1) > .form-control |
        // usuariodeprueba@mail.es
        driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control"))
                .sendKeys("usuariodeprueba@mail.es");
        // 7 | waitForElementPresent | css=.form-group:nth-child(2) > .form-control |
        // 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions
                    .presenceOfElementLocated(By.cssSelector(".form-group:nth-child(2) > .form-control")));
        }
        // 8 | click | css=.form-group:nth-child(2) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
        // 9 | type | css=.form-group:nth-child(2) > .form-control | 12345
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("12345");
        // 10 | waitForElementPresent | css=.ajax-button | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".ajax-button")));
        }
        // 11 | click | css=.ajax-button |
        driver.findElement(By.cssSelector(".ajax-button")).click();
        // 12 | pause | 1000 |
        // Pausa extra, porque hay veces que el wait for element clickable no es
        // suficiente
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 13 | assertText | css=.text-danger | The credentials you entered are not
        // associated with an account. Please check your email and/or password and try
        // again.
        assertThat(driver.findElement(By.cssSelector(".text-danger")).getText(), is(
                "The credentials you entered are not associated with an account. Please check your email and/or password and try again."));
        // 14 | close | |
        driver.close();
    }

    @Test
    public void loginincorrectbademailformat() {
        // Test name: Login incorrect bad email format
        // Step # | name | target | value
        // 1 | open | http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/ |
        driver.get("http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/");
        // 2 | waitForElementPresent | linkText=Log in | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Log in")));
        }
        // 3 | click | linkText=Log in |
        driver.findElement(By.linkText("Log in")).click();
        // 4 | waitForElementPresent | css=.form-group:nth-child(1) > .form-control |
        // 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions
                    .presenceOfElementLocated(By.cssSelector(".form-group:nth-child(1) > .form-control")));
        }
        // 5 | click | css=.form-group:nth-child(1) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
        // 6 | type | css=.form-group:nth-child(1) > .form-control | usuariodeprueba
        driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).sendKeys("usuariodeprueba");
        // 7 | waitForElementPresent | css=.form-group:nth-child(2) > .form-control |
        // 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions
                    .presenceOfElementLocated(By.cssSelector(".form-group:nth-child(2) > .form-control")));
        }
        // 8 | click | css=.form-group:nth-child(2) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
        // 9 | type | css=.form-group:nth-child(2) > .form-control | 12345
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("12345");
        // 10 | waitForElementPresent | css=.ajax-button | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".ajax-button")));
        }
        // 11 | click | css=.ajax-button |
        driver.findElement(By.cssSelector(".ajax-button")).click();
        // 12 | executeScript | return document.querySelector("#login > div > div > form
        // > div:nth-child(1) > input").validationMessage | message
        vars.put("message", js.executeScript(
                "return document.querySelector(\"#login > div > div > form > div:nth-child(1) > input\").validationMessage"));
        // 13 | pause | 1000 |
        // Pausa extra, porque hay veces que el wait for element clickable no es
        // suficiente
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 14 | assert | message | Incluye un signo "@" en la dirección de correo
        // electrónico. La dirección "usuariodeprueba" no incluye el signo "@".
        if (browser == 1) {
            assertEquals(vars.get("message").toString(),
                    "Incluye un signo \"@\" en la dirección de correo electrónico. La dirección \"usuariodeprueba\" no incluye el signo \"@\".");

        } else {
            assertEquals(vars.get("message").toString(), "Introduzca una dirección de correo.");
        }
        // 15 | close | |
        driver.close();
    }

    @Test
    public void loginincorrectemptyemail() {
        // Test name: Login incorrect empty email
        // Step # | name | target | value
        // 1 | open | http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/ |
        driver.get("http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/");
        // 2 | waitForElementPresent | linkText=Log in | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Log in")));
        }
        // 3 | click | linkText=Log in |
        driver.findElement(By.linkText("Log in")).click();
        // 4 | waitForElementPresent | css=.form-group:nth-child(1) > .form-control |
        // 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions
                    .presenceOfElementLocated(By.cssSelector(".form-group:nth-child(1) > .form-control")));
        }
        // 5 | click | css=.form-group:nth-child(1) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
        // 6 | type | css=.form-group:nth-child(1) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).clear();
        // 7 | waitForElementPresent | css=.form-group:nth-child(2) > .form-control |
        // 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions
                    .presenceOfElementLocated(By.cssSelector(".form-group:nth-child(2) > .form-control")));
        }
        // 8 | click | css=.form-group:nth-child(2) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
        // 9 | type | css=.form-group:nth-child(2) > .form-control | 12345
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).sendKeys("12345");
        // 10 | waitForElementPresent | css=.ajax-button | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".ajax-button")));
        }
        // 11 | click | css=.ajax-button |
        driver.findElement(By.cssSelector(".ajax-button")).click();
        // 12 | pause | 1000 |
        // Pausa extra, porque hay veces que el wait for element clickable no es
        // suficiente
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 13 | assertText | css=.invalid-feedback | Please provide a valid email
        // address.
        assertThat(driver.findElement(By.cssSelector(".invalid-feedback")).getText(),
                is("Please provide a valid email address."));
        // 14 | close | |
        driver.close();
    }

    @Test
    public void loginincorrectemptypass() {
        // Test name: Login incorrect empty pass
        // Step # | name | target | value
        // 1 | open | http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/ |
        driver.get("http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/");
        // 2 | waitForElementPresent | linkText=Log in | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Log in")));
        }
        // 3 | click | linkText=Log in |
        driver.findElement(By.linkText("Log in")).click();
        // 4 | waitForElementPresent | css=.form-group:nth-child(1) > .form-control |
        // 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions
                    .presenceOfElementLocated(By.cssSelector(".form-group:nth-child(1) > .form-control")));
        }
        // 5 | click | css=.form-group:nth-child(1) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control")).click();
        // 6 | type | css=.form-group:nth-child(1) > .form-control |
        // usuariodeprueba@mail.es
        driver.findElement(By.cssSelector(".form-group:nth-child(1) > .form-control"))
                .sendKeys("usuariodeprueba@mail.es");
        // 7 | waitForElementPresent | css=.form-group:nth-child(2) > .form-control |
        // 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions
                    .presenceOfElementLocated(By.cssSelector(".form-group:nth-child(2) > .form-control")));
        }
        // 8 | click | css=.form-group:nth-child(2) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).click();
        // 9 | type | css=.form-group:nth-child(2) > .form-control |
        driver.findElement(By.cssSelector(".form-group:nth-child(2) > .form-control")).clear();
        // 10 | waitForElementPresent | css=.ajax-button | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".ajax-button")));
        }
        // 11 | click | css=.ajax-button |
        driver.findElement(By.cssSelector(".ajax-button")).click();
        // 12 | pause | 1000 |
        // Pausa extra, porque hay veces que el wait for element clickable no es
        // suficiente
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 13 | assertText | css=.invalid-feedback | Please enter your password.
        assertThat(driver.findElement(By.cssSelector(".invalid-feedback")).getText(),
                is("Please enter your password."));
        // 14 | close | |
        driver.close();
    }
}
