package org.ual.hmis.ortega2;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SailsSignUpTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    // Browser selector
    int browser = 1; // 0: firefox, 1: chrome,...

    @Before
    public void setUp() {
        Boolean headless = true;
        switch (browser) {
        case 0: // firefox
            // Firefox
            // Descargar geckodriver de https://github.com/mozilla/geckodriver/releases
            // Descomprimir el archivo geckodriver.exe en la carpeta drivers

            System.setProperty("webdriver.gecko.driver", "drivers/geckodriver.exe");
            FirefoxOptions firefoxOptions = new FirefoxOptions();
            if (headless)
                firefoxOptions.setHeadless(headless);
            driver = new FirefoxDriver(firefoxOptions);

            break;
        case 1: // chrome
            // Chrome
            // Descargar Chromedriver de https://chromedriver.chromium.org/downloads
            // Descomprimir el archivo chromedriver.exe en la carpeta drivers

            System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
            ChromeOptions chromeOptions = new ChromeOptions();
            if (headless)
                chromeOptions.setHeadless(headless);
            chromeOptions.addArguments("window-size=1920,1080");
            driver = new ChromeDriver(chromeOptions);

            break;

        default:
            fail("Please select a browser");
            break;
        }
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        if (browser == 1)
            driver.quit();
    }

    @Test
    public void signupcorrect() {
        // Test name: Sign up correct
        // Step # | name | target | value
        // 1 | executeScript | return "ual-"+Math.floor(Math.random()*1500000)+"@ual.es"
        // | emailrandom
        vars.put("emailrandom", js.executeScript("return \"ual-\"+Math.floor(Math.random()*1500000)+\"@ual.es\""));
        // 2 | open | http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/ |
        driver.get("http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/");
        // 3 | waitForElementPresent | linkText=Sign up | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Sign up")));
        }
        // 4 | click | linkText=Sign up |
        driver.findElement(By.linkText("Sign up")).click();
        // 5 | pause | 1000 |
        // Pausa extra, porque hay veces que el wait for element clickable no es
        // suficiente
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 6 | waitForElementPresent | id=full-name | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("full-name")));
        }
        // 7 | click | id=full-name |
        driver.findElement(By.id("full-name")).click();
        // 8 | type | id=full-name | correcto
        driver.findElement(By.id("full-name")).sendKeys("correcto");
        // 9 | waitForElementPresent | id=email-address | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("email-address")));
        }
        // 10 | click | id=email-address |
        driver.findElement(By.id("email-address")).click();
        // 11 | type | id=email-address | ${emailrandom}
        driver.findElement(By.id("email-address")).sendKeys(vars.get("emailrandom").toString());
        // 12 | waitForElementPresent | id=password | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("password")));
        }
        // 13 | click | id=password |
        driver.findElement(By.id("password")).click();
        // 14 | type | id=password | 123456
        driver.findElement(By.id("password")).sendKeys("123456");
        // 15 | waitForElementPresent | id=confirm-password | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("confirm-password")));
        }
        // 16 | click | id=confirm-password |
        driver.findElement(By.id("confirm-password")).click();
        // 17 | type | id=confirm-password | 123456
        driver.findElement(By.id("confirm-password")).sendKeys("123456");
        // 18 | click | id=terms-agreement |
        driver.findElement(By.id("terms-agreement")).click();
        // 19 | click | css=.ajax-button |
        driver.findElement(By.cssSelector(".ajax-button")).click();
        // 20 | waitForElementPresent | id=header-account-menu-link | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("header-account-menu-link")));
        }
        // 21 | click | id=header-account-menu-link |
        driver.findElement(By.id("header-account-menu-link")).click();
        // 22 | waitForElementPresent | linkText=Sign out | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Sign out")));
        }
        // 23 | click | linkText=Sign out |
        driver.findElement(By.linkText("Sign out")).click();
        // 24 | pause | 1000 |
        // Pausa extra, porque hay veces que el wait for element clickable no es
        // suficiente
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 25 | close | |
        driver.close();
    }

    @Test
    public void signupfailbademailformat() {
        // Test name: Sign up fail bad email format
        // Step # | name | target | value
        // 1 | open | http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/ |
        driver.get("http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/");
        // 2 | waitForElementPresent | linkText=Sign up | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Sign up")));
        }
        // 3 | click | linkText=Sign up |
        driver.findElement(By.linkText("Sign up")).click();
        // 4 | pause | 1000 |
        // Pausa extra, porque hay veces que el wait for element clickable no es
        // suficiente
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 5 | waitForElementPresent | id=full-name | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("full-name")));
        }
        // 6 | click | id=full-name |
        driver.findElement(By.id("full-name")).click();
        // 7 | type | id=full-name | Usuario de prueba
        driver.findElement(By.id("full-name")).sendKeys("Usuario de prueba");
        // 8 | waitForElementPresent | id=email-address | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("email-address")));
        }
        // 9 | click | id=email-address |
        driver.findElement(By.id("email-address")).click();
        // 10 | type | id=email-address | usuariodeprueba
        driver.findElement(By.id("email-address")).sendKeys("usuariodeprueba");
        // 11 | waitForElementPresent | id=password | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("password")));
        }
        // 12 | click | id=password |
        driver.findElement(By.id("password")).click();
        // 13 | type | id=password | 123456
        driver.findElement(By.id("password")).sendKeys("123456");
        // 14 | waitForElementPresent | id=confirm-password | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("confirm-password")));
        }
        // 15 | click | id=confirm-password |
        driver.findElement(By.id("confirm-password")).click();
        // 16 | type | id=confirm-password | 123456
        driver.findElement(By.id("confirm-password")).sendKeys("123456");
        // 17 | click | id=terms-agreement |
        driver.findElement(By.id("terms-agreement")).click();
        // 18 | click | css=.ajax-button |
        driver.findElement(By.cssSelector(".ajax-button")).click();
        // 19 | executeScript | return
        // document.getElementById("email-address").validationMessage | message
        vars.put("message", js.executeScript("return document.getElementById(\"email-address\").validationMessage"));
        // 20 | pause | 1000 |
        // Pausa para la ejecución del script
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 21 | assert | message | Incluye un signo "@" en la dirección de correo
        // electrónico. La dirección "usuariodeprueba" no incluye el signo "@".
        if (browser == 1) {
            assertEquals(vars.get("message").toString(),
                    "Incluye un signo \"@\" en la dirección de correo electrónico. La dirección \"usuariodeprueba\" no incluye el signo \"@\".");

        } else {
            assertEquals(vars.get("message").toString(), "Introduzca una dirección de correo.");
        }
        // 22 | close | |
        driver.close();
    }

    @Test
    public void signupfailuseralreadyexists() {
        // Test name: Sign up fail user already exists
        // Step # | name | target | value
        // 1 | open | http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/ |
        driver.get("http://hmis06-sailsapp.eastus2.cloudapp.azure.com:1337/");
        // 2 | waitForElementPresent | linkText=Sign up | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Sign up")));
        }
        // 3 | click | linkText=Sign up |
        driver.findElement(By.linkText("Sign up")).click();
        // 4 | pause | 1000 |
        // Pausa extra, porque hay veces que el wait for element clickable no es
        // suficiente
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 5 | waitForElementPresent | id=full-name | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("full-name")));
        }
        // 6 | click | id=full-name |
        driver.findElement(By.id("full-name")).click();
        // 7 | type | id=full-name | Usuario de prueba
        driver.findElement(By.id("full-name")).sendKeys("Usuario de prueba");
        // 8 | waitForElementPresent | id=email-address | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("email-address")));
        }
        // 9 | click | id=email-address |
        driver.findElement(By.id("email-address")).click();
        // 10 | type | id=email-address | usuariodeprueba@mail.es
        driver.findElement(By.id("email-address")).sendKeys("usuariodeprueba@mail.es");
        // 11 | waitForElementPresent | id=password | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("password")));
        }
        // 12 | click | id=password |
        driver.findElement(By.id("password")).click();
        // 13 | type | id=password | 123456
        driver.findElement(By.id("password")).sendKeys("123456");
        // 14 | waitForElementPresent | id=confirm-password | 30000
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.presenceOfElementLocated(By.id("confirm-password")));
        }
        // 15 | click | id=confirm-password |
        driver.findElement(By.id("confirm-password")).click();
        // 16 | type | id=confirm-password | 123456
        driver.findElement(By.id("confirm-password")).sendKeys("123456");
        // 17 | click | id=terms-agreement |
        driver.findElement(By.id("terms-agreement")).click();
        // 18 | click | css=.ajax-button |
        driver.findElement(By.cssSelector(".ajax-button")).click();
        // 19 | pause | 1000 |
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        // 20 | assertElementPresent | xpath=//*[@id="signup"]/div/div/form/div[6] |
        {
            List<WebElement> elements = driver.findElements(By.xpath("//*[@id=\"signup\"]/div/div/form/div[6]"));
            assert (elements.size() > 0);
        }
        // 21 | close | |
        driver.close();
    }
}
